//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Media;

namespace VentSystems.Model
{
    using System;
    using System.Collections.Generic;
    using System;
    using System.Drawing;
    using System.IO;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int Count { get; set; }
        public int StorageId { get; set; }
        public int SupplierId { get; set; }
        public byte[] Image { get; set; }

        public string ImageSource
        {
            get
            {
                return $"data:image/png;base64,{Convert.ToBase64String(Image)}";
            }
        }
    
        public virtual Storages Storages { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
